#pragma once
#include <string>
#include <time.h>
#include "../src/gsoap_autogenerated/soapStub.h"

using namespace std;

namespace DePlaguarism{

	struct DocHeader {
		t__type type;
		tm dateTime;
		size_t textName_len;
		size_t authorName_len;
		size_t authorGroup_len;
		size_t data_len;
	};

	struct TextDocument
	{
		DocHeader header;
		string name,
			authorName,
			authorGroup,
			data;
		int number;

		TextDocument(const t__text & m, int num);
		TextDocument(){};
	};

	//TextDocument * getShingleAppText(const t__text & m);
}


