#pragma once
#include <string>
#include "../src/gsoap_autogenerated/soapStub.h"
#include <time.h>

using namespace std;

namespace shingleAppStaff{

	struct ShingleAppText
	{
		string name,
			authorName,
			authorGroup;
		t__type type;
		int number;
		tm dateTime;

		ShingleAppText(const t__text & m);
		ShingleAppText(){};
	};

	//ShingleAppText * getShingleAppText(const t__text & m);
}

